# Generated by Django 3.0 on 2020-01-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_companydetail_reliability_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='Average_maintenance_cost',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
