# Generated by Django 3.0 on 2020-01-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carcomponents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarComponents',
            new_name='CarComponent',
        ),
    ]
