# Generated by Django 3.0 on 2020-01-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200117_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarComponent',
        ),
    ]
