# Generated by Django 3.0 on 2020-01-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carcomponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('airConditioning', models.IntegerField()),
                ('breakingSystem', models.IntegerField()),
                ('coolingSystem', models.IntegerField()),
                ('electrical', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('fuelSystem', models.IntegerField()),
                ('gearBox', models.IntegerField()),
                ('steeringSystem', models.IntegerField()),
                ('transmission', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
